### ISSUE TITLE
有关.CSV

### ISSUE THREAD

**Issue by xautzhaozhe** [yuchaoY/CNND#1]
"labels_pred = np.loadtxt(data_name+'.csv', delimiter=',')"请问一下，这个.CSV文件在哪可以下载

**Comment by yuchaoY** [comment]
My fault. It's used have for my testing and should been deleted. And now, I fixed it.

**Comment by yuchaoY** [comment]
> "labels_pred = np.loadtxt(data_name+'.csv', delimiter=',')"请问一下，这个.CSV文件在哪可以下载
My fault. It's used for my test and should have been deleted. And now, I fixed it.

**Comment by xautzhaozhe** [comment]
谢谢你，你的代码对我很有用，请问你也是做高光谱异常检测的吗





---原始邮件---
发件人: "Yuchao Yuan"<notifications@github.com&gt;
发送时间: 2020年1月1日(周三) 晚上8:09
收件人: "yuchaoY/CNND"<CNND@noreply.github.com&gt;;
抄送: "zhaozhe"<3325677863@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [yuchaoY/CNND] 有关.CSV (#1)



My fault. It's used have for my testing and should been deleted. And now, I fixed it.
